### ISSUE TITLE
How to add new fonts

### ISSUE THREAD

**Issue by Abdelalihub** [CamelCaseName/HUB75nano#10]
Hello,

Thanks again for the library.

Just wondering, how to add other fonts? Adafruit_GFX has many fonts, is it possible to add them to this library? if so, how?

Kind regards,

**Comment by CamelCaseName** [comment]
Hi, for adding fonts you want to know how the single pixels are output from the library. then "copy" them into the pixel buffer to the desired coordinates. should be pretty easy, but i think that they may be to big for the display(size).
