### ISSUE TITLE
pic2led.exe

### ISSUE THREAD

**Issue by Abdelalihub** [CamelCaseName/HUB75nano#11]
I've tried using the pci2led tool, and pasted the picture path, but nothing happened ! just the cmd window closing.

I have tested with a 64x32 image.

Kind regards,

**Comment by CamelCaseName** [comment]
Hi again, do you get any output from the console?

**Comment by CamelCaseName** [comment]
![image](https://user-images.githubusercontent.com/48067449/116794274-13f7f680-aacc-11eb-8639-71dc43763421.png)
that's the ouptu i am getting, just checked

**Comment by CamelCaseName** [comment]
tho you have to change the type from LEDx8 to LED

**Comment by CamelCaseName** [comment]
closed due to inactivity
