### ISSUE TITLE
Arduino Pro mini not supported despite is Nano compatible

### ISSUE THREAD

**Issue by lrtsenar** [CamelCaseName/HUB75nano#23]
I try to compile this project for Arduino Pro Mini which is a Nano without USB port.
It works under ATmega328p like Nano.
I think "ARDUINO_AVR_PRO" has to be added to board.h (line 7) like following :

```#if defined ARDUINO_AVR_NANO || defined ARDUINO_AVR_PRO```

Thanks in advance

**Comment by CamelCaseName** [comment]
Hi, is the pinout for the pro mini the same? If it is you could just give it a try, I can look into it next week regardless

**Comment by lrtsenar** [comment]
As I said, they're identical, including pinout. The only difference is the USB port present on Nano. I have several versions of Pro Mini and they're compatible w/ Nano.

**Comment by lrtsenar** [comment]
For information, the modification has to be set in board_methods.h too, at line 20.
I can't wait for you to add support for 2 linked panels, for example 2 x (64 x 32) ;-)

**Comment by CamelCaseName** [comment]
alright, added the pro mini to the library (v2.3.2)
