### ISSUE TITLE
Write Big Chars on Panel

### ISSUE THREAD

**Issue by fcabrera23** [CamelCaseName/HUB75nano#3]
Hi, I was checking your library and its not possible to write a big string, like for example 10:30 in the whole LED display. Do you have any function for that?

**Comment by CamelCaseName** [comment]
Hi, unfortunately I only have the small font (5x3) implemented..

You could set every pixel the number should use manually/in a function, but apart from that, I have nothing for this. Sorry. But I am currently working on a new project, which will bring some improvement to this one also

**Comment by CamelCaseName** [comment]
you can take a look at my Word clock example, which displays characters on the panel, but very small ones.

**Comment by fcabrera23** [comment]
Hi, thanks for your quick response. I would be willing to pay for the deployment, do you think you can make it? I need this asap

**Comment by fcabrera23** [comment]
My idea es showing a text like  " 23.5 | 76%" which is the temp and humidity. Thanks

**Comment by CamelCaseName** [comment]
i added a function with a scaling factor for the font it currently uses, so you can have big chars, but still blocky. just call it stylized and done

**Comment by fcabrera23** [comment]
Hi, @CamelCaseName  thanks for all your help. I have just tried and getting some errors with the display. Im attaching prictures


![IMG_0286 copy](https://user-images.githubusercontent.com/21229385/101165756-f3f40200-3615-11eb-9aaf-10d1e5e88558.jpg)

![IMG_0287 copy](https://user-images.githubusercontent.com/21229385/101165801-05d5a500-3616-11eb-86fd-0c3e868550d9.jpg)

**Comment by CamelCaseName** [comment]
ok, this looks weird. i saw something similar with my tries yesterday, and i got it solved by reducing ram usage. can you please check in the "panel.h" whether  "#define BIG" is commented or not. if you comment this line, you can only set the first 8 colors(0-7), but it might fix this problem. with the BIG statement set, the buffer uses two bits per pixel, which comes out to a total of nearly 95% ram usage, which doesn't always work. with only one bit per pixel, you have about 800bytes of ram to work with. it might also be the wiring,  there is nothing more I can think of right now.

if you take a look at the "word clock example", there should be some info on the ram issues.

i could also try to reduce variables used, but it is getting kind of complicated

**Comment by CamelCaseName** [comment]
the one thing that is extra weird is the fact, that the letters are along the short side, which I have no idea on how they got there. 

i might look into a vertical mode as well, but I can not guarantee anything

**Comment by fcabrera23** [comment]
Thanks.. I was using horizontal mode, just took the picture in a vertical mode. I will try your solution and let you know tomorrow.

**Comment by CamelCaseName** [comment]
i tried your code with both big and small buffer, and it had no effect.
![IMG_20201207_150143](https://user-images.githubusercontent.com/48067449/101360113-7fcb8f80-389d-11eb-9e48-5e2d7b4258f5.jpg)
the number looks normal, even the small red bar at the top is kind of normal, i dont know where these bleeds come from, or how to get rid of them. the only thing i think might cause your problem are wrongly connected row select lines.

i included your code in the exampe, so you can try also

have fun
